steps:
  - block: "Request Release"
    fields:
      - text: "Code Name"
        key: "release-name"
        hint: "What’s the code name for this release? :name_badge:"
        required: true
        default: "Release #"
  - label: "test2"
    command: 'buildkite-agent meta-data get "release-name"'
    agents:
    - "queue=discoball"
  - label: "test3"
    command: 'buildkite-agent meta-data get "release-name"'
    agents:
    - "queue=discoball"
