steps:
  - block: "Request Release"
    fields:
      - text: "ar-ad-manager version"
        key: "release-version"
        hint: "What’s the ar-ad-manager version number? :name_badge:"
        required: true
        default: "13.5.1"
  - command:
      - 'export VERSION=$(buildkite-agent meta-data get "release-version")'
      - 'echo $VERSION'
    label: "Bizflow :moneybag:"
    plugins:
      - ssh://git@github.com/buildkite-plugins/docker-buildkite-plugin#v3.2.0:
          image: "node:8"
          workdir: /app
          mount-ssh-agent: true
          propagate-environment: true
    agents:
      - "queue=discoball"
