steps:
  - block: "Request Release"
    fields:
      - text: "Code Name"
        key: "release-name"
        hint: "What’s the code name for this release? :name_badge:"
        required: true
        default: "Release #"
  - command: "echo 'hello'"
    label: ":pipeline:"
    agents:
    - "queue=discoball"


