steps:
  - block: "Request Release"
    fields:
      - text: "Code Name"
        key: "release-name"
        hint: "What’s the code name for this release? :name_badge:"
        required: true
        default: "Release #"
  - command:
    - "sleep 2m"
    - "echo 'hello'
    label: ":clown:"
    agents:
    - "queue=discoball"
  - command: "echo 'too'"
    label: ":car:"
    agents:
    - "queue=discoball"'


